export const GameStates = {
    START_SCREEN: 'START_SCREEN',
    GAME_IN_PROGRESS: 'GAME_IN_PROGRESS',
    END_SCREEN: 'END_SCREEN'
}

export const GuessingState = {
    GUESSING: 'GUESSING',
    WORD_COMPLETED: 'WORD_COMPLETED',
    WORD_FAILED: 'WORD_FAILED'
}

export const DEFAULT_GAME_LENGTH = 60;
export const DEFAULT_GUESSES_ALLOWED = 6;